name: marine-heatwave-cookbook-dev
channels:
  - conda-forge
dependencies:
  - jupyter-book
  - jupyterlab
  - jupyter_server
  - python>=3.10
  - cftime
  - numpy
  - xarray
  - matplotlib
  - pydap
  - dask
  - ipywidgets
  - plotly
  - pip
  - pip:
      - sphinx-pythia-theme
